### PR TITLE
proofread chapter05-ch

### PR DESCRIPTION
**Pull request by tornoteli**
To understand what is "Mr. Miyagi's fence lesson" and give a better translation, I went to watch The Karate Kid! Haha :D

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
: )
hehehhehe

Like it?

**Comment by tornoteli** [comment]
Yep, but if I were Daniel I'd like to follow Mr. Miyagi to learn how to trim the plants more :D

**Comment by patriciogonzalezvivo** [comment]
My wife just give me a bonsai for my Birthday... so I'm start learning how to trim, pinch and repot. Do you know?

**Comment by tornoteli** [comment]
Wow cool! Sorry I'm primary school level of it  : P

**Pull request merged**
