### PR TITLE
fr: chapter 6 + 1 typo in 'en'

### PR DESCRIPTION
**Pull request by nicoptere**

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
perfect! thanks!

**Comment by nicoptere** [comment]
I got a bit lost in pull requests here :/ 
this https://github.com/patriciogonzalezvivo/thebookofshaders/pull/68/commits/c6d0a751f31cf6ddb77cb3c810df2b575ca38e27 contains the 'additions' about the vectors.

**Comment by nicoptere** [comment]
well if this works, I wil have no clue as to why...

**Comment by patriciogonzalezvivo** [comment]
👍

**Comment by nicoptere** [comment]
lol ^^

**Pull request merged**
