### PR TITLE
Create a TravisCI configuration to check PDF building of the book

### PR DESCRIPTION
**Pull request by yvan-sraka**
I worked a bit on this last night and now I am facing a dilemma and I would like your opinion @patriciogonzalezvivo:

This configuration is quite simple, I just have to build `glfw` and `glfwViewer` by hand because these two programs are not available in the standard Ubuntu Trusty repositories, which is the distribution used by default by Travis CI.

And I have to add `texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended` to the dependencies to avoid the following two problems:

```
Successful building of ./book.tex
pandoc: Error producing PDF from TeX source.
! Font T1/cmr/m/n/10=ecrm1000 at 10.0pt not loadable: Metric (TFM) file or inst
alled font not found.
<to be read again> 
                   relax 
l.100 \fontencoding\encodingdefault\selectfont
Error in building of ./book.pdf
```

```
Successful building of ./book.tex
pandoc: Error producing PDF from TeX source.
! LaTeX Error: File `etoolbox.sty' not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
Enter file name: 
! Emergency stop.
<read *> 
l.8 \RequirePackage
Error in building of ./book.pdf
```

So maybe it might be a good idea to add them to the Raspberry Pi section of the Appendix because I'm pretty sure these packages are needed and are not delivered by default with Raspbian ...

And now after fixing these issues, I'm stuck with the following error:

```
Successful building of ./book.tex
pandoc: Error producing PDF from TeX source.
! Unable to load picture or PDF file './04/glslEditor-01.gif'.
<to be read again> 
                   }
l.722 \includegraphics{./04/glslEditor-01.gif}
Error in building of ./book.pdf
```

Yes, it is somewhat obvious that the GIF image format can not be used by the XeTeX PDF output engine.

It is therefore necessary to choose between:
- convert all the `.gif` to `.png` in the `parseBook.py` script with something like `iconv`,
- or use a Latex package like [`movie9`](http://pages.uoregon.edu/noeckel/PDFmovie.html) to include animations in the PDF (I'm not sure my Kindle reader can handle this).

What do you think I should do?

Thank you,

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Hi! First of all thank you for taking your time to do this! I really appreciate it! Defenetly the way to go is to transform gif to jpg or png. 
Regarding glslViewer last year the nice folks of raspian add glslViewer to the official repository. I should double check that that still true. Also we maybe should cut another release with the last improvements.  Do you know How hard would be to add glslViewer to ubuntu Tutsi? Your solution is the correct one, I m trying to think more longer term : )

**Comment by yvan-sraka** [comment]
Hum ... I think the simplest solution, without dealing with [the official Ubuntu team](
https://launchpad.net/ubuntu), is to [register a project on launchpad](https://launchpad.net/projects/+new) and [activate a PPA](https://help.launchpad.net/Packaging/PPA) :wink:!

**Comment by patriciogonzalezvivo** [comment]
That's a great idea! thanks

**Comment by yvan-sraka** [comment]
Okay, so I fixed the GIF problem :smile:!

Now I am faced with:

```
Successful building of ./book.tex
pandoc: Error producing PDF from TeX source.
! Dimension too large.
<to be read again> 
                   b
l.4860 \includegraphics{./13/holdsworth.jpg}
Error in building of ./book.pdf
```

According to your answer to issue  https://github.com/patriciogonzalezvivo/thebookofshaders/issues/60, I could just delete folders `>= 12` in the TravisCI script, but it's a bit dirty ... maybe we can create a rule like "delete all folders which contain the empty file `.unfinished`"?

What do you think?

**Comment by patriciogonzalezvivo** [comment]
Sounds good

**Comment by yvan-sraka** [comment]
I could open two issues to follow up on the remaining work:
- one to create an Ubuntu PPA repository (+ update the section of the book describing the compilation of the PDF file and use it in the Travis CI script) ;
- another to update the `parseBook.py` Python script to ignore the chapters containing the `.unfinished` file.

The last thing to remember is to [activate the repository on Travis CI](https://travis-ci.org/patriciogonzalezvivo/thebookofshaders)!

**Pull request merged**
