### PR TITLE
Add translation of some chapters in portuguese.

### PR DESCRIPTION
**Pull request by luuchowl**

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Hi! thanks for your time. Do you mind resolving the conflicts?

**Comment by luuchowl** [comment]
Hello, I blended these versions. Thanks!

**Comment by luuchowl** [comment]
Hello, I just added a translation for Shaping functions.

**Comment by patriciogonzalezvivo** [comment]
THANKS

**Pull request merged**
