### PR TITLE
[WIP] Update Appendix 2 with a FAQ following issues #12 & #13

### PR DESCRIPTION
**Pull request by yvan-sraka**
Hello,

Because I wrote "by @cansik and @MartinRGB", I need your opinion on what I copied from issues #12 and #13!

I also think we need to remove some content because some problems are now automatically corrected by the [/src/parseBook.py](https://github.com/patriciogonzalezvivo/thebookofshaders/blob/master/src/parseBook.py) script or can be easily corrected by it. But we need to keep the explanations on what this script does and what dependencies need to be installed depending on the version of MacOSX.

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Let's do

**Comment by patriciogonzalezvivo** [comment]
Hi! What's the state of this?

**Comment by yvan-sraka** [comment]
Still waiting for a review by @cansik and/or @MartinRGB as I just copy/pasted their words!

**Comment by cansik** [comment]
@yvan-sraka Sorry for the late reply. I currently do not have the time to check it, do you have a MacOS to build it? Maybe I find a little time to try it now with the new build script.

**Comment by julien** [comment]
Unfortunately, the build is broken on mac os

**Pull request closed without merging**
