### PR TITLE
add readme-ch

### PR DESCRIPTION
**Pull request by tornoteli**
Starting to translate the book into Chinese!

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Excellent!! THANKS! Who is working on this translation? (could I have a list of names?) How is the best way to give credits? (twitter, websites) thanks again!!!

**Comment by Artrustee** [comment]
THANKS to Paul and Jason!!! They are great mentors who gives a good start on openFrameworks and...SHADERS!!! Actually me and Tong are currently working on first round translation,and there would be 10 ppl around to proofread. So actually we can call it "of course" teams' translation. YEAH!!! 
and almost forget to THANKS to u, Patricio, it's u who make this happen make us enable to translate!

**Comment by tornoteli** [comment]
Thanks Patricio! Me(Tong Li) and Artrustee(Yi Zhang) are working on the translation (you can find us on facebook), and a bunch of people helped proofread including professors, senior developers and guys major in En-Ch translation. We'll make a list when finishing the first round of translation, since there are more and more people helping us : ) And thanks to Paul and Jason.

**Comment by kynd** [comment]
Hey, I wasn't aware this is going on. It's so cool to see the book is spreading to much broader audience!
Just wanted to say hello from jp translator;)
kynd(www.kynd.info)

**Comment by patriciogonzalezvivo** [comment]
This is great! Thanks so much for it!

**Comment by patriciogonzalezvivo** [comment]
I add the link to your translation! YAY! how it looks? http://www.thebookofshaders.com/ ?

**Comment by patriciogonzalezvivo** [comment]
Please tellme if you want to be mention on other way, or if someone else start working on it so I can put him on the credits

**Comment by tornoteli** [comment]
Thanks Patricio! I was doing my translation today when I refreshed the website and suddenly saw my name on it! Such a surprise : )  I see the Chinese ver, it looks great! Though we could adjust the font and font_size later : D

**Comment by tornoteli** [comment]
Hi kynd : ) Really love your work. Glad to meet you .

**Comment by patriciogonzalezvivo** [comment]
I'm glad you like it. Translating is a big effort. I'm super thankful for it. Let me know if you need something else : )
Did you notice that you can adjust your own CSS for your translation here? https://github.com/patriciogonzalezvivo/thebookofshaders/tree/master/css

**Comment by tornoteli** [comment]
Oh : ) I'll check it out. Haha thanks.

**Pull request merged**
